const $=s=>document.querySelector(s);let pages=[],selected=new Set(),wizardStep=0,expandedNamespaces=new Set();
function toast(m){const t=$('#toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2600)}
async function api(url,opt){const r=await fetch(url,opt);if(!r.ok)throw new Error(await r.text());return r.headers.get('content-type')?.includes('json')?r.json():r}
async function status(){const s=await api('/api/status');$('#pagesCount').textContent=s.pages.toLocaleString('de-DE');$('#mediaCount').textContent=s.media.toLocaleString('de-DE');$('#lastScan').textContent=s.lastScan?new Date(s.lastScan).toLocaleString('de-DE'):'Noch nicht'}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#title').textContent={dashboard:'Migrationsübersicht',pages:'Seiten & Namespaces',plugins:'Plugin-Inventar'}[id];if(id==='pages')loadPages()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
$('#scan').onclick=async()=>{const b=$('#scan');b.disabled=true;b.textContent='Scan läuft …';try{const x=await api('/api/scans',{method:'POST'});toast(`${x.pages} Seiten und ${x.media} Medien erfasst`);await status();await loadPages()}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='Wiki scannen'}};
function namespacePath(id){const parts=String(id||'').split(':').filter(Boolean);return parts.slice(0,-1)}
function pageName(id){const parts=String(id||'').split(':').filter(Boolean);return parts[parts.length-1]||id}
function addNamespace(root,path){let node=root;let full='';path.forEach(part=>{full=full?full+':'+part:part;if(!node.children.has(part))node.children.set(part,{kind:'folder',name:part,path:full,children:new Map(),pages:[]});node=node.children.get(part)})}
function buildTree(items){const root={kind:'root',children:new Map(),pages:[]};items.forEach(p=>{const path=namespacePath(p.ID);addNamespace(root,path);let node=root;path.forEach(part=>{node=node.children.get(part)});node.pages.push(p)});return root}
function renderTree(root,query){const tree=$('#pageTree');const autoExpand=Boolean(query.trim());if(autoExpand){for(const p of pages){let path=namespacePath(p.ID),full='';path.forEach(part=>{full=full?full+':'+part:part;expandedNamespaces.add(full)})}}const fragment=document.createDocumentFragment();const renderNode=(node,depth)=>{const folders=[...node.children.values()].sort((a,b)=>a.name.localeCompare(b.name,'de'));folders.forEach(folder=>{const open=autoExpand||expandedNamespaces.has(folder.path);const row=document.createElement('div');row.className='tree-row folder-row';row.style.setProperty('--depth',depth);row.setAttribute('role','treeitem');row.setAttribute('aria-expanded',open?'true':'false');const toggle=document.createElement('button');toggle.className='tree-toggle';toggle.type='button';toggle.textContent=open?'▾':'▸';toggle.setAttribute('aria-label',open?'Namespace einklappen':'Namespace aufklappen');toggle.onclick=e=>{e.stopPropagation();if(expandedNamespaces.has(folder.path))expandedNamespaces.delete(folder.path);else expandedNamespaces.add(folder.path);renderTree(root,$('#search').value)};const icon=document.createElement('span');icon.className='tree-icon folder-icon';icon.textContent='▰';const label=document.createElement('span');label.className='tree-label';label.textContent=folder.name;label.title=folder.path;row.append(toggle,icon,label);fragment.appendChild(row);if(open)renderNode(folder,depth+1)});const leafs=[...node.pages].sort((a,b)=>(a.Title||pageName(a.ID)).localeCompare(b.Title||pageName(b.ID),'de'));leafs.forEach(p=>{const row=document.createElement('div');row.className='tree-row page-row';row.style.setProperty('--depth',depth);row.dataset.id=p.ID;row.setAttribute('role','treeitem');const cb=document.createElement('input');cb.type='checkbox';cb.checked=selected.has(p.ID);cb.title='Seite für Export auswählen';cb.onclick=e=>{e.stopPropagation();e.target.checked?selected.add(p.ID):selected.delete(p.ID);selection();wizard()};const icon=document.createElement('span');icon.className='tree-icon page-icon';icon.textContent='▤';const label=document.createElement('span');label.className='tree-label';label.textContent=p.Title||pageName(p.ID);label.title=p.ID;const meta=document.createElement('span');meta.className='tree-meta';const includes=p.Includes?.length||0,warnings=p.Warnings?.length||0;if(includes){const b=document.createElement('span');b.className='tree-badge';b.textContent=`I ${includes}`;b.title=`${includes} Include(s)`;meta.appendChild(b)}if(warnings){const b=document.createElement('span');b.className='tree-badge warning';b.textContent=`! ${warnings}`;b.title=`${warnings} Warnung(en)`;meta.appendChild(b)}row.append(cb,icon,label,meta);row.onclick=()=>detail(p.ID);fragment.appendChild(row)})};renderNode(root,0);tree.replaceChildren(fragment);$('#treeCount').textContent=`${items.length} Seite${items.length===1?'':'n'}`}
async function loadPages(){pages=await api('/api/pages?q='+encodeURIComponent($('#search').value));renderTree(buildTree(pages),$('#search').value);plugins()}
async function detail(id){const x=await api('/api/pages/'+encodeURIComponent(id));const p=x.page;$('#detail').innerHTML=`<h2>${esc(p.Title)}</h2><div class="meta">${esc(p.ID)} · ${p.Includes?.length||0} Includes · ${p.Media?.length||0} Medien · ${p.Warnings?.length||0} Warnungen</div><div class="tabs"><button class="active">Vorschau</button><button>Source</button><button>Migration</button></div><div id="tabbody" class="preview">${x.preview}</div>`;const bs=document.querySelectorAll('.tabs button');bs.forEach((b,i)=>b.onclick=async()=>{bs.forEach(x=>x.classList.remove('active'));b.classList.add('active');if(i===0){$('#tabbody').className='preview';$('#tabbody').innerHTML=x.preview}else if(i===1){$('#tabbody').className='';$('#tabbody').innerHTML=`<pre>${esc(p.Source)}</pre>`}else{$('#tabbody').className='migration-preview';$('#tabbody').innerHTML=`<h3>Für Confluence vorbereitet</h3><p><b>${p.Media?.length||0}</b> Medien werden als Attachment-Referenzen vorbereitet.</p><p><b>${p.Includes?.length||0}</b> Includes bleiben als <code>[DOKUWIKI INCLUDE: …]</code> erhalten.</p><p>Die zukünftige Seitenstruktur wird nicht automatisch festgelegt.</p>`}})}
function plugins(){const m={};pages.forEach(p=>(p.Plugins||[]).forEach(x=>{m[x]??={count:0,pages:new Set()};m[x].count++;m[x].pages.add(p.ID)}));$('#pluginRows').innerHTML=Object.entries(m).map(([n,v])=>`<tr><td><strong>${esc(n)}</strong></td><td>${v.count}</td><td>${v.pages.size}</td><td>${['include','wrap','anchor'].includes(n)?'Unterstützt':'Unbekannt / prüfen'}</td></tr>`).join('')||'<tr><td colspan="4">Noch keine Plugins erfasst.</td></tr>'}
function selection(){$('#selection').textContent=selected.size+' ausgewählt';$('#export').disabled=!selected.size}
function bindWizardActions(){const body=$('#wizardBody');const next=body?.querySelector('[data-wizard-next]');if(next)next.onclick=()=>{wizardStep=Number(next.dataset.wizardNext);wizard()};const exportButton=body?.querySelector('[data-wizard-export]');if(exportButton)exportButton.onclick=doExport}
function wizard(){const w=$('#wizard');if(!selected.size){w.classList.add('hidden');return}w.classList.remove('hidden');const chosen=pages.filter(p=>selected.has(p.ID)),media=chosen.reduce((n,p)=>n+(p.Media?.length||0),0),includes=chosen.reduce((n,p)=>n+(p.Includes?.length||0),0),warnings=chosen.reduce((n,p)=>n+(p.Warnings?.length||0),0);document.querySelectorAll('.wizardsteps span').forEach((s,i)=>s.classList.toggle('active',i===wizardStep));if(wizardStep===0){$('#wizardBody').innerHTML=`<h3>1 · Auswahl prüfen</h3><p>${chosen.length} Seite(n) ausgewählt.</p><div class="summary"><span><b>${media}</b> Medien</span><span><b>${includes}</b> Includes</span><span><b>${warnings}</b> Warnungen</span></div><button class="primary" data-wizard-next="1">Prüfung starten →</button>`}else if(wizardStep===1){$('#wizardBody').innerHTML=`<h3>2 · Übernahme prüfen</h3><p>Confluence-Storage-Dateien und exakte Attachment-Namen werden erzeugt. Includes werden <b>nicht</b> auf neue Seiten aufgelöst.</p>${includes?`<div class="notice"><strong>${includes} Include-Platzhalter</strong><p>Diese werden erst nach Kenntnis der neuen Confluence-Struktur ersetzt.</p></div>`:''}${warnings?`<div class="notice warning"><strong>${warnings} Warnungen</strong><p>Unbekannte Plugins oder andere Besonderheiten bitte vor der Übernahme prüfen.</p></div>`:'<p>Keine Parser-Warnungen.</p>'}<button class="primary" data-wizard-next="2">Export vorbereiten →</button>`}else{$('#wizardBody').innerHTML=`<h3>3 · Export</h3><p>Der Export enthält pro Seite HTML, Markdown, Confluence-Storage-Format, Originalquelle, Anhänge und CSV-Zuordnungen.</p><button class="primary" data-wizard-export>ZIP erstellen und herunterladen</button>`}bindWizardActions()}
async function doExport(){try{const r=await fetch('/api/exports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'dokuwiki-confluence-migration',pages:[...selected]})});if(!r.ok)throw new Error(await r.text());const a=document.createElement('a');a.href=URL.createObjectURL(await r.blob());a.download='dokuwiki-confluence-migration.zip';a.click();URL.revokeObjectURL(a.href);toast('Migrationsexport erstellt')}catch(e){toast(e.message)}}
let timer;$('#search').oninput=()=>{clearTimeout(timer);timer=setTimeout(loadPages,250)};$('#export').onclick=()=>{wizardStep=0;wizard()};
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}status().catch(e=>toast(e.message));
