const $=s=>document.querySelector(s);let pages=[],selected=new Set();
function toast(m){const t=$('#toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2600)}
async function api(url,opt){const r=await fetch(url,opt);if(!r.ok)throw new Error(await r.text());return r.headers.get('content-type')?.includes('json')?r.json():r}
async function status(){const s=await api('/api/status');$('#pagesCount').textContent=s.pages.toLocaleString('de-DE');$('#mediaCount').textContent=s.media.toLocaleString('de-DE');$('#lastScan').textContent=s.lastScan?new Date(s.lastScan).toLocaleString('de-DE'):'Noch nicht'}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#title').textContent={dashboard:'Migrationsübersicht',pages:'Seiten & Namespaces',plugins:'Plugin-Inventar'}[id];if(id==='pages')loadPages()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
$('#scan').onclick=async()=>{const b=$('#scan');b.disabled=true;b.textContent='Scan läuft …';try{const x=await api('/api/scans',{method:'POST'});toast(`${x.pages} Seiten und ${x.media} Medien erfasst`);await status();await loadPages()}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='Wiki scannen'}};
async function loadPages(){pages=await api('/api/pages?q='+encodeURIComponent($('#search').value));$('#pageRows').innerHTML=pages.map(p=>`<tr data-id="${esc(p.ID)}"><td><input type="checkbox" ${selected.has(p.ID)?'checked':''}></td><td><strong>${esc(p.Title)}</strong><br><small>${esc(p.ID)}</small></td><td>${esc(p.Namespace||'–')}</td><td>${p.Includes?.length||0}</td><td>${p.Warnings?.length||0}</td></tr>`).join('');document.querySelectorAll('#pageRows tr').forEach(tr=>{tr.onclick=e=>{if(e.target.type==='checkbox'){e.stopPropagation();e.target.checked?selected.add(tr.dataset.id):selected.delete(tr.dataset.id);selection()}else detail(tr.dataset.id)}});plugins()}
async function detail(id){const x=await api('/api/pages/'+encodeURIComponent(id));const p=x.page;$('#detail').innerHTML=`<h2>${esc(p.Title)}</h2><div class="meta">${esc(p.ID)} · ${p.Includes?.length||0} Includes · ${p.Media?.length||0} Medien · ${p.Warnings?.length||0} Warnungen</div><div class="tabs"><button class="active">Vorschau</button><button>Source</button><button>Dependencies</button></div><div id="tabbody" class="preview">${x.preview}</div>`;const bs=document.querySelectorAll('.tabs button');bs.forEach((b,i)=>b.onclick=()=>{bs.forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tabbody').className=i===1?'':'preview';$('#tabbody').innerHTML=i===0?x.preview:i===1?`<pre>${esc(p.Source)}</pre>`:`<h3>Includes</h3>${(p.Includes||[]).map(v=>`<div class="include">${esc(v.Target)}</div>`).join('')||'<p>Keine Includes.</p>'}`})}
function plugins(){const m={};pages.forEach(p=>(p.Plugins||[]).forEach(x=>{m[x]??={count:0,pages:0};m[x].count++;m[x].pages++}));$('#pluginRows').innerHTML=Object.entries(m).map(([n,v])=>`<tr><td><strong>${esc(n)}</strong></td><td>${v.count}</td><td>${v.pages}</td><td>${['include','wrap','anchor'].includes(n)?'Unterstützt':'Unbekannt / prüfen'}</td></tr>`).join('')||'<tr><td colspan="4">Noch keine Plugins erfasst.</td></tr>'}
function selection(){$('#selection').textContent=selected.size+' ausgewählt';$('#export').disabled=!selected.size}
let timer;$('#search').oninput=()=>{clearTimeout(timer);timer=setTimeout(loadPages,250)};$('#export').onclick=async()=>{try{const r=await fetch('/api/exports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'dokuwiki-migration',pages:[...selected]})});if(!r.ok)throw new Error(await r.text());const a=document.createElement('a');a.href=URL.createObjectURL(await r.blob());a.download='dokuwiki-migration.zip';a.click();URL.revokeObjectURL(a.href);toast('Export erstellt')}catch(e){toast(e.message)}};
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}status().catch(e=>toast(e.message));
