const $=s=>document.querySelector(s);let pages=[],selected=new Set(),wizardStep=0;
function toast(m){const t=$('#toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2600)}
async function api(url,opt){const r=await fetch(url,opt);if(!r.ok)throw new Error(await r.text());return r.headers.get('content-type')?.includes('json')?r.json():r}
async function status(){const s=await api('/api/status');$('#pagesCount').textContent=s.pages.toLocaleString('de-DE');$('#mediaCount').textContent=s.media.toLocaleString('de-DE');$('#lastScan').textContent=s.lastScan?new Date(s.lastScan).toLocaleString('de-DE'):'Noch nicht'}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#title').textContent={dashboard:'Migrationsübersicht',pages:'Seiten & Namespaces',plugins:'Plugin-Inventar'}[id];if(id==='pages')loadPages()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
$('#scan').onclick=async()=>{const b=$('#scan');b.disabled=true;b.textContent='Scan läuft …';try{const x=await api('/api/scans',{method:'POST'});toast(`${x.pages} Seiten und ${x.media} Medien erfasst`);await status();await loadPages()}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='Wiki scannen'}};
async function loadPages(){pages=await api('/api/pages?q='+encodeURIComponent($('#search').value));$('#pageRows').innerHTML=pages.map(p=>`<tr data-id="${esc(p.ID)}"><td><input type="checkbox" ${selected.has(p.ID)?'checked':''}></td><td><strong>${esc(p.Title)}</strong><br><small>${esc(p.ID)}</small></td><td>${esc(p.Namespace||'–')}</td><td>${p.Includes?.length||0}</td><td>${p.Warnings?.length||0}</td></tr>`).join('');document.querySelectorAll('#pageRows tr').forEach(tr=>{tr.onclick=e=>{if(e.target.type==='checkbox'){e.stopPropagation();e.target.checked?selected.add(tr.dataset.id):selected.delete(tr.dataset.id);selection();wizard()}else detail(tr.dataset.id)}});plugins()}
async function detail(id){const x=await api('/api/pages/'+encodeURIComponent(id));const p=x.page;$('#detail').innerHTML=`<h2>${esc(p.Title)}</h2><div class="meta">${esc(p.ID)} · ${p.Includes?.length||0} Includes · ${p.Media?.length||0} Medien · ${p.Warnings?.length||0} Warnungen</div><div class="tabs"><button class="active">Vorschau</button><button>Source</button><button>Migration</button></div><div id="tabbody" class="preview">${x.preview}</div>`;const bs=document.querySelectorAll('.tabs button');bs.forEach((b,i)=>b.onclick=async()=>{bs.forEach(x=>x.classList.remove('active'));b.classList.add('active');if(i===0){$('#tabbody').className='preview';$('#tabbody').innerHTML=x.preview}else if(i===1){$('#tabbody').className='';$('#tabbody').innerHTML=`<pre>${esc(p.Source)}</pre>`}else{$('#tabbody').className='migration-preview';$('#tabbody').innerHTML=`<h3>Für Confluence vorbereitet</h3><p><b>${p.Media?.length||0}</b> Medien werden als Attachment-Referenzen vorbereitet.</p><p><b>${p.Includes?.length||0}</b> Includes bleiben als <code>[DOKUWIKI INCLUDE: …]</code> erhalten.</p><p>Die zukünftige Seitenstruktur wird nicht automatisch festgelegt.</p>`}})}
function plugins(){const m={};pages.forEach(p=>(p.Plugins||[]).forEach(x=>{m[x]??={count:0,pages:new Set()};m[x].count++;m[x].pages.add(p.ID)}));$('#pluginRows').innerHTML=Object.entries(m).map(([n,v])=>`<tr><td><strong>${esc(n)}</strong></td><td>${v.count}</td><td>${v.pages.size}</td><td>${['include','wrap','anchor'].includes(n)?'Unterstützt':'Unbekannt / prüfen'}</td></tr>`).join('')||'<tr><td colspan="4">Noch keine Plugins erfasst.</td></tr>'}
function selection(){$('#selection').textContent=selected.size+' ausgewählt';$('#export').disabled=!selected.size}
function setWizardStep(step){wizardStep=step;wizard()}
function wizard(){const w=$('#wizard');if(!selected.size){w.classList.add('hidden');return}w.classList.remove('hidden');const chosen=pages.filter(p=>selected.has(p.ID));const media=chosen.reduce((n,p)=>n+(p.Media?.length||0),0),includes=chosen.reduce((n,p)=>n+(p.Includes?.length||0),0),warnings=chosen.reduce((n,p)=>n+(p.Warnings?.length||0),0);document.querySelectorAll('.wizardsteps span').forEach((s,i)=>s.classList.toggle('active',i===wizardStep));if(wizardStep===0){$('#wizardBody').innerHTML=`<h3>1 · Auswahl prüfen</h3><p>${chosen.length} Seite(n) ausgewählt.</p><div class="summary"><span><b>${media}</b> Medien</span><span><b>${includes}</b> Includes</span><span><b>${warnings}</b> Warnungen</span></div><button class="primary" onclick="setWizardStep(1)">Prüfung starten →</button>`}else if(wizardStep===1){$('#wizardBody').innerHTML=`<h3>2 · Übernahme prüfen</h3><p>Confluence-Storage-Dateien und exakte Attachment-Namen werden erzeugt. Includes werden <b>nicht</b> auf neue Seiten aufgelöst.</p>${includes?`<div class="notice"><strong>${includes} Include-Platzhalter</strong><p>Diese werden erst nach Kenntnis der neuen Confluence-Struktur ersetzt.</p></div>`:''}${warnings?`<div class="notice warning"><strong>${warnings} Warnungen</strong><p>Unbekannte Plugins oder andere Besonderheiten bitte vor der Übernahme prüfen.</p></div>`:'<p>Keine Parser-Warnungen.</p>'}<button class="primary" onclick="setWizardStep(2)">Export vorbereiten →</button>`}else{$('#wizardBody').innerHTML=`<h3>3 · Export</h3><p>Der Export enthält pro Seite HTML, Markdown, Confluence-Storage-Format, Originalquelle, Anhänge und CSV-Zuordnungen.</p><button class="primary" onclick="doExport()">ZIP erstellen und herunterladen</button>`}}
async function doExport(){try{const r=await fetch('/api/exports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'dokuwiki-confluence-migration',pages:[...selected]})});if(!r.ok)throw new Error(await r.text());const a=document.createElement('a');a.href=URL.createObjectURL(await r.blob());a.download='dokuwiki-confluence-migration.zip';a.click();URL.revokeObjectURL(a.href);toast('Migrationsexport erstellt')}catch(e){toast(e.message)}}
let timer;$('#search').oninput=()=>{clearTimeout(timer);timer=setTimeout(loadPages,250)};$('#export').onclick=()=>{wizardStep=0;wizard()};
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}status().catch(e=>toast(e.message));
