package render

import("strings";"testing";"github.com/TimUx/Doku-Wiki-Confluence_migration/internal/model")
func TestConfluenceStorageRendersPageIncludesAsNativeMacro(t *testing.T){p:=model.Page{ID:"server:backup",Nodes:[]model.Node{{Type:"heading",Level:"2",Text:"Backup"},{Type:"include",Target:"server:restore",Meta:map[string]string{"mode":"page"}}},Includes:[]model.Reference{{Target:"server:restore",Kind:"page"}}};got:=ConfluenceStorage(p);if !strings.Contains(got,"<ac:structured-macro ac:name=\"include\">"){t.Fatalf("include macro missing: %s",got)};if !strings.Contains(got,"<ri:page ri:content-title=\"restore\"/>"){t.Fatalf("include target missing: %s",got)};if strings.Contains(got,"[DOKUWIKI INCLUDE"){t.Fatalf("page include must not remain a placeholder: %s",got)};if !strings.Contains(got,"<ac:structured-macro ac:name=\"toc\"/>"){t.Fatalf("toc macro missing: %s",got)}}
func TestConfluenceStoragePreservesNonPageIncludePlaceholder(t *testing.T){p:=model.Page{ID:"server:backup",Nodes:[]model.Node{{Type:"include",Target:"server:restore",Meta:map[string]string{"mode":"section"}}}};got:=ConfluenceStorage(p);if !strings.Contains(got,"[DOKUWIKI INCLUDE section: server:restore]"){t.Fatalf("non-page include placeholder missing: %s",got)};if strings.Contains(got,"ac:name=\"include\""){t.Fatalf("section include must not be guessed as page include: %s",got)}}
func TestConfluencePageTitleFromDokuWikiID(t *testing.T){if got:=confluencePageTitle("2.2.3:kng_switche_-_service_beschreibung");got!="kng switche - service beschreibung"{t.Fatalf("unexpected title: %q",got)}}
func TestAttachmentNamesCollisionIsDeterministic(t *testing.T){p:=model.Page{Media:[]model.Reference{{Target:"one:image.png"},{Target:"two:image.png"}}};got:=AttachmentNames(p);if got["one:image.png"]!="image.png"||got["two:image.png"]!="image_2.png"{t.Fatalf("unexpected names: %#v",got)}}
func TestConfluenceStorageRendersExternalAndSamePageLinks(t *testing.T){p:=model.Page{ID:"storage:security",Nodes:[]model.Node{{Type:"heading",Level:"2",Text:"Datensicherheit"},{Type:"paragraph",Text:`[[https://example.com/security.pdf|Security PDF]] [[#datensicherheit|Zum Abschnitt]] [[storage:other|Andere Seite]]`}}};got:=ConfluenceStorage(p);if !strings.Contains(got,"<a href=\"https://example.com/security.pdf\">Security PDF</a>"){t.Fatalf("external link missing: %s",got)};if !strings.Contains(got,"<a href=\"#datensicherheit\">Zum Abschnitt</a>"){t.Fatalf("same-page link missing: %s",got)};if !strings.Contains(got,"[DOKUWIKI LINK: storage:other]"){t.Fatalf("internal-page placeholder missing: %s",got)}}
func TestPreviewRendersNestedMediaLink(t *testing.T){p:=model.Page{ID:"cc33:storage:howto:block:pure:active-cluster",Nodes:[]model.Node{{Type:"paragraph",Text:`[[https://example.com/wiki/lib/exe/detail.php/cc33:storage:howto:block:pure:pod_1.png|{{https://example.com/wiki/lib/exe/fetch.php/cc33:storage:howto:block:pure:pod_1.png?400}}]]`}}};got:=PreviewHTML(p);if strings.Contains(got,"[[https://"){t.Fatalf("raw wiki link remains: %s",got)};if !strings.Contains(got,"<a href=\"https://example.com/wiki/lib/exe/detail.php/cc33:storage:howto:block:pure:pod_1.png\""){t.Fatalf("image detail link missing: %s",got)};if !strings.Contains(got,"/api/media?target=cc33%3Astorage%3Ahowto%3Ablock%3Apure%3Apod_1.png"){t.Fatalf("media endpoint target missing: %s",got)}}
func TestWrapMapsToNativeConfluenceMacros(t *testing.T){p:=model.Page{ID:"demo",Nodes:[]model.Node{{Type:"wrap",Plugin:"wrap",Meta:map[string]string{"kind":"info"},Children:[]model.Node{{Type:"paragraph",Text:"Information"}}},{Type:"wrap",Plugin:"wrap",Meta:map[string]string{"kind":"spoiler"},Children:[]model.Node{{Type:"paragraph",Text:"Geheimer Inhalt"}}},{Type:"wrap",Plugin:"wrap",Meta:map[string]string{"kind":"box"},Children:[]model.Node{{Type:"paragraph",Text:"Box"}}}}};got:=ConfluenceStorage(p);for _,want:=range []string{"ac:name=\"info\"","ac:name=\"expand\"","ac:name=\"panel\""}{if !strings.Contains(got,want){t.Fatalf("macro %s missing: %s",want,got)}}}
func TestNoTocControlSuppressesGeneratedToc(t *testing.T){p:=model.Page{ID:"demo",Nodes:[]model.Node{{Type:"control",Plugin:"notoc"},{Type:"heading",Level:"2",Text:"Ohne TOC"}}};got:=ConfluenceStorage(p);if strings.Contains(got,"ac:name=\"toc\""){t.Fatalf("toc must be suppressed: %s",got)}}
