package render

import("fmt";"html";"path/filepath";"regexp";"strings";"github.com/TimUx/Doku-Wiki-Confluence_migration/internal/model")
var confluenceMedia=regexp.MustCompile(`\{\{\s*([^}|?]+)(?:\?[^}|]*)?(?:\|([^}]*))?\s*\}\}`)
var confluenceLink=regexp.MustCompile(`\[\[([^\]|]+)(?:\|([^\]]+))?\]\]`)
var confluenceBold=regexp.MustCompile(`\*\*(.+?)\*\*`);var confluenceItalic=regexp.MustCompile(`//([^/\n]+?)//`);var confluenceUnderline=regexp.MustCompile(`__(.+?)__`);var confluenceMono=regexp.MustCompile(`''(.+?)''`);var confluenceStrike=regexp.MustCompile(`~~(.+?)~~`);var confluenceFootnote=regexp.MustCompile(`\(\((.+?)\)\)`);var confluenceSub=regexp.MustCompile(`_(\{[^}]+\}|\w+)`);var confluenceSup=regexp.MustCompile(`\^(\{[^}]+\}|\w+)`)
func AttachmentNames(p model.Page)map[string]string{out:=map[string]string{};used:=map[string]int{};for _,ref:=range p.Media{if _,ok:=out[ref.Target];ok{continue};name:=filepath.Base(strings.ReplaceAll(ref.Target,":","/"));if name=="."||name==""{name="attachment"};var b strings.Builder;for _,r:=range name{if(r>='a'&&r<='z')||(r>='A'&&r<='Z')||(r>='0'&&r<='9')||strings.ContainsRune("._-",r){b.WriteRune(r)}else{b.WriteByte('_')}};name=b.String();key:=strings.ToLower(name);used[key]++;if used[key]>1{ext:=filepath.Ext(name);name=strings.TrimSuffix(name,ext)+fmt.Sprintf("_%d",used[key])+ext};out[ref.Target]=name};return out}
func ConfluenceStorage(p model.Page)string{a:=AttachmentNames(p);var b strings.Builder;if !hasControl(p,"notoc"){b.WriteString("<ac:structured-macro ac:name=\"toc\"/>\n")};for i:=0;i<len(p.Nodes);i++{n:=p.Nodes[i];switch n.Type{case "heading":fmt.Fprintf(&b,"<ac:structured-macro ac:name=\"anchor\"><ac:parameter ac:name=\"\">%s</ac:parameter></ac:structured-macro><h%s>%s</h%s>\n",html.EscapeString(anchorID(n.Text)),n.Level,storageInline(n.Text,p,a),n.Level);case "paragraph":fmt.Fprintf(&b,"<p>%s</p>\n",storageInline(n.Text,p,a));case "bullet_item","ordered_item":renderListsStorage(&b,p.Nodes,&i,p,a);case "table_row":renderTableStorage(&b,p.Nodes,&i,p,a);case "quote":fmt.Fprintf(&b,"<blockquote><p>%s</p></blockquote>\n",storageInline(n.Text,p,a));case "hr":b.WriteString("<hr/>\n");case "code":renderCodeStorage(&b,n);case "info","warning","note":renderCalloutStorage(&b,n,p,a);case "wrap":renderWrapStorage(&b,n,p,a);case "include":renderIncludeStorage(&b,n);case "nowiki":fmt.Fprintf(&b,"<pre>%s</pre>\n",html.EscapeString(n.Text));case "control":case "unknown_plugin":fmt.Fprintf(&b,"<p><strong>Unsupported plugin: %s</strong></p><pre>%s</pre>\n",html.EscapeString(n.Plugin),html.EscapeString(n.Raw))}};return b.String()}
func renderIncludeStorage(b *strings.Builder,n model.Node){mode:="page";if n.Meta!=nil&&n.Meta["mode"]!=""{mode=strings.ToLower(n.Meta["mode"])};if mode!="page"&&mode!="include"{fmt.Fprintf(b,"<p>[DOKUWIKI INCLUDE %s: %s]</p>\n",html.EscapeString(mode),html.EscapeString(n.Target));return};title:=confluencePageTitle(n.Target);fmt.Fprintf(b,"<ac:structured-macro ac:name=\"include\"><ac:parameter ac:name=\"\"><ac:link><ri:page ri:content-title=\"%s\"/></ac:link></ac:parameter></ac:structured-macro>\n",html.EscapeString(title))}
func confluencePageTitle(target string)string{target=strings.TrimSpace(target);if i:=strings.LastIndex(target,":");i>=0{target=target[i+1:]};target=strings.ReplaceAll(target,"_"," ");return strings.TrimSpace(target)}
func hasControl(p model.Page,name string)bool{for _,n:=range p.Nodes{if n.Type=="control"&&strings.EqualFold(n.Plugin,name){return true}};return false}
func renderListsStorage(b *strings.Builder,nodes []model.Node,i *int,p model.Page,a map[string]string){htmlList:=func(start int)string{return renderListLevelStorage(nodes,&start,0,p,a)};_ = htmlList;start:=*i;fmt.Fprintf(b,"%s",renderListLevelStorage(nodes,&start,nodeIndent(nodes[start]),p,a));*i=start-1}
func renderListLevelStorage(nodes []model.Node,i *int,indent int,p model.Page,a map[string]string)string{if *i>=len(nodes)||!isListNode(nodes[*i]){return ""};typ:=nodes[*i].Type;tag:="ul";if typ=="ordered_item"{tag="ol"};var b strings.Builder;fmt.Fprintf(&b,"<%s>",tag);for *i<len(nodes){n:=nodes[*i];if !isListNode(n){break};level:=nodeIndent(n);if level<indent{break};if level>indent{if b.Len()>0{b.WriteString("</li>")};b.WriteString(renderListLevelStorage(nodes,i,level,p,a));if *i>=len(nodes){break};continue};if n.Type!=typ{break};fmt.Fprintf(&b,"<li>%s",storageInline(n.Text,p,a));(*i)++;if *i<len(nodes)&&isListNode(nodes[*i])&&nodeIndent(nodes[*i])>indent{b.WriteString(renderListLevelStorage(nodes,i,nodeIndent(nodes[*i]),p,a));b.WriteString("</li>")}else{b.WriteString("</li>")}};fmt.Fprintf(&b,"</%s>",tag);return b.String()}
func isListNode(n model.Node)bool{return n.Type=="bullet_item"||n.Type=="ordered_item"}
func renderTableStorage(b *strings.Builder,nodes []model.Node,i *int,p model.Page,a map[string]string){b.WriteString("<table><tbody>\n");for *i<len(nodes)&&nodes[*i].Type=="table_row"{b.WriteString("<tr>");for _,c:=range nodes[*i].Children{tag:="td";if c.Type=="table_header"{tag="th"};span:="";if c.Meta!=nil&&c.Meta["colspan"]!=""{span=` colspan="`+html.EscapeString(c.Meta["colspan"])+`"`};fmt.Fprintf(b,"<%s%s>%s</%s>",tag,span,storageInline(c.Text,p,a),tag)};b.WriteString("</tr>\n");(*i)++};b.WriteString("</tbody></table>\n");(*i)--}
func renderCodeStorage(b *strings.Builder,n model.Node){lang:="";if n.Meta!=nil{lang=n.Meta["language"]};code:=strings.ReplaceAll(n.Text,"]]>","]]]]><![CDATA[>");fmt.Fprintf(b,"<ac:structured-macro ac:name=\"code\">");if lang!=""{fmt.Fprintf(b,"<ac:parameter ac:name=\"language\">%s</ac:parameter>",html.EscapeString(lang))};b.WriteString("<ac:plain-text-body><![CDATA[");b.WriteString(code);b.WriteString("]]></ac:plain-text-body></ac:structured-macro>\n")}
func renderCalloutStorage(b *strings.Builder,n model.Node,p model.Page,a map[string]string){macro:="note";if n.Meta!=nil{switch strings.ToLower(n.Meta["kind"]){case "info","tip","warning","note":macro=strings.ToLower(n.Meta["kind"])}};fmt.Fprintf(b,"<ac:structured-macro ac:name=\"%s\"><ac:rich-text-body><p>%s</p></ac:rich-text-body></ac:structured-macro>\n",macro,storageInline(n.Text,p,a))}
func renderWrapStorage(b *strings.Builder,n model.Node,p model.Page,a map[string]string){kind:="";classes:="";if n.Meta!=nil{kind=strings.ToLower(n.Meta["kind"]);classes=n.Meta["classes"]};switch kind{case "info","tip","warning","note":fmt.Fprintf(b,"<ac:structured-macro ac:name=\"%s\"><ac:rich-text-body>%s</ac:rich-text-body></ac:structured-macro>\n",kind,wrapBodyStorage(n,p,a));return;case "important","notice","help","danger","safety","alert","caution":macro:="note";if kind=="danger"||kind=="safety"||kind=="alert"||kind=="caution"{macro="warning"};fmt.Fprintf(b,"<ac:structured-macro ac:name=\"%s\"><ac:rich-text-body>%s</ac:rich-text-body></ac:structured-macro>\n",macro,wrapBodyStorage(n,p,a));return;case "box":fmt.Fprintf(b,"<ac:structured-macro ac:name=\"panel\"><ac:rich-text-body>%s</ac:rich-text-body></ac:structured-macro>\n",wrapBodyStorage(n,p,a));return;case "spoiler","hide":title:="Details";if kind=="hide"{title="Verborgener Inhalt"};fmt.Fprintf(b,"<ac:structured-macro ac:name=\"expand\"><ac:parameter ac:name=\"title\">%s</ac:parameter><ac:rich-text-body>%s</ac:rich-text-body></ac:structured-macro>\n",title,wrapBodyStorage(n,p,a));return;case "group":renderSectionStorage(b,n,p,a);return;case "clear":return};fmt.Fprintf(b,"<div class=\"dokuwiki-wrap %s\">%s</div>\n",html.EscapeString(classes),wrapBodyStorage(n,p,a))}
func wrapBodyStorage(n model.Node,p model.Page,a map[string]string)string{var b strings.Builder;for _,c:=range n.Children{switch c.Type{case "paragraph":fmt.Fprintf(&b,"<p>%s</p>",storageInline(c.Text,p,a));case "heading":fmt.Fprintf(&b,"<h%s>%s</h%s>",c.Level,storageInline(c.Text,p,a),c.Level);case "bullet_item":fmt.Fprintf(&b,"<ul><li>%s</li></ul>",storageInline(c.Text,p,a));case "ordered_item":fmt.Fprintf(&b,"<ol><li>%s</li></ol>",storageInline(c.Text,p,a));case "table_row":b.WriteString("<table><tr>");for _,cell:=range c.Children{tag:="td";if cell.Type=="table_header"{tag="th"};fmt.Fprintf(&b,"<%s>%s</%s>",tag,storageInline(cell.Text,p,a),tag)};b.WriteString("</tr></table>");case "wrap":renderWrapStorage(&b,c,p,a);case "include":renderIncludeStorage(&b,c);default:if c.Text!=""{fmt.Fprintf(&b,"<p>%s</p>",storageInline(c.Text,p,a))}}};return b.String()}
func renderSectionStorage(b *strings.Builder,n model.Node,p model.Page,a map[string]string){b.WriteString("<ac:structured-macro ac:name=\"section\"><ac:rich-text-body>");found:=false;for _,c:=range n.Children{if c.Type=="wrap"&&hasClass(c,"column"){found=true;b.WriteString("<ac:structured-macro ac:name=\"column\">");if c.Meta!=nil&&c.Meta["width"]!=""{fmt.Fprintf(b,"<ac:parameter ac:name=\"width\">%s</ac:parameter>",html.EscapeString(c.Meta["width"]))};fmt.Fprintf(b,"<ac:rich-text-body>%s</ac:rich-text-body></ac:structured-macro>",wrapBodyStorage(c,p,a))}};if !found{fmt.Fprintf(b,"<ac:structured-macro ac:name=\"column\"><ac:rich-text-body>%s</ac:rich-text-body></ac:structured-macro>",wrapBodyStorage(n,p,a))};b.WriteString("</ac:rich-text-body></ac:structured-macro>\n")}
func hasClass(n model.Node,class string)bool{if n.Meta==nil{return false};for _,c:=range strings.Fields(strings.ToLower(n.Meta["classes"])){if c==class{return true}};return false}
func nodeIndent(n model.Node)int{v:=0;if n.Meta!=nil{fmt.Sscanf(n.Meta["indent"],"%d",&v)};return v}
func storageInline(s string,p model.Page,a map[string]string)string{out:=html.EscapeString(s);out=confluenceLink.ReplaceAllStringFunc(out,func(raw string)string{m:=confluenceLink.FindStringSubmatch(html.UnescapeString(raw));if len(m)==0{return raw};target:=normalizeURL(m[1]);label:=m[2];if label==""{label=target};if isExternalLink(target){return fmt.Sprintf(`<a href="%s">%s</a>`,html.EscapeString(target),storageInline(label,p,a))};if strings.HasPrefix(strings.TrimSpace(target),"#"){return fmt.Sprintf(`<a href="#%s">%s</a>`,html.EscapeString(anchorID(strings.TrimPrefix(strings.TrimSpace(target),"#"))),storageInline(label,p,a))};return fmt.Sprintf(`<span>[DOKUWIKI LINK: %s]</span>`,html.EscapeString(resolveTarget(p.ID,target)))})
out=confluenceMedia.ReplaceAllStringFunc(out,func(raw string)string{m:=confluenceMedia.FindStringSubmatch(html.UnescapeString(raw));if len(m)==0{return raw};target:=normalizeMediaTarget(resolveTarget(p.ID,m[1]));name:=a[target];if name==""{name=filepath.Base(strings.ReplaceAll(target,":","/"))};return fmt.Sprintf(`<ac:image><ri:attachment ri:filename="%s"/></ac:image>`,html.EscapeString(name))});out=confluenceFootnote.ReplaceAllStringFunc(out,func(raw string)string{m:=confluenceFootnote.FindStringSubmatch(html.UnescapeString(raw));if len(m)==0{return raw};return `<sup class="footnote">`+storageInline(m[1],p,a)+`</sup>`});out=confluenceSub.ReplaceAllString(out,`<sub>$1</sub>`);out=confluenceSup.ReplaceAllString(out,`<sup>$1</sup>`);out=confluenceBold.ReplaceAllString(out,`<strong>$1</strong>`);out=confluenceItalic.ReplaceAllString(out,`<em>$1</em>`);out=confluenceUnderline.ReplaceAllString(out,`<u>$1</u>`);out=confluenceMono.ReplaceAllString(out,`<code>$1</code>`);out=confluenceStrike.ReplaceAllString(out,`<del>$1</del>`);return out}
