package render

import (
 "fmt"
 "html"
 "path/filepath"
 "regexp"
 "strings"
 "github.com/TimUx/Doku-Wiki-Confluence_migration/internal/model"
)
var confluenceMedia=regexp.MustCompile(`\{\{\s*([^}|?]+)(?:\?[^}|]*)?(?:\|([^}]*))?\s*\}\}`)
var confluenceLink=regexp.MustCompile(`\[\[([^\]|]+)(?:\|([^\]]+))?\]\]`)
var confluenceBold=regexp.MustCompile(`\*\*(.+?)\*\*`)
var confluenceItalic=regexp.MustCompile(`//([^/\n]+?)//`)
var confluenceUnderline=regexp.MustCompile(`__(.+?)__`)
var confluenceMono=regexp.MustCompile(`''(.+?)''`)
var confluenceStrike=regexp.MustCompile(`~~(.+?)~~`)
var confluenceFootnote=regexp.MustCompile(`\(\((.+?)\)\)`)

func AttachmentNames(p model.Page)map[string]string{out:=map[string]string{};used:=map[string]int{};for _,ref:=range p.Media{if _,ok:=out[ref.Target];ok{continue};name:=filepath.Base(strings.ReplaceAll(ref.Target,":","/"));if name=="."||name==""{name="attachment"};var b strings.Builder;for _,r:=range name{if(r>='a'&&r<='z')||(r>='A'&&r<='Z')||(r>='0'&&r<='9')||strings.ContainsRune("._-",r){b.WriteRune(r)}else{b.WriteByte('_')}};name=b.String();key:=strings.ToLower(name);used[key]++;if used[key]>1{ext:=filepath.Ext(name);name=strings.TrimSuffix(name,ext)+fmt.Sprintf("_%d",used[key])+ext};out[ref.Target]=name};return out}

func ConfluenceStorage(p model.Page)string{attachments:=AttachmentNames(p);var b strings.Builder;b.WriteString(`<ac:structured-macro ac:name="toc"/>`+"\n");for _,n:=range p.Nodes{switch n.Type{case "heading":fmt.Fprintf(&b,`<h%s id="%s">%s</h%s>\n`,n.Level,anchorID(n.Text),storageInline(n.Text,p,attachments),n.Level);case "paragraph":fmt.Fprintf(&b,"<p>%s</p>\n",storageInline(n.Text,p,attachments));case "bullet_item":fmt.Fprintf(&b,"<ul><li>%s</li></ul>\n",storageInline(n.Text,p,attachments));case "ordered_item":fmt.Fprintf(&b,"<ol><li>%s</li></ol>\n",storageInline(n.Text,p,attachments));case "quote":fmt.Fprintf(&b,"<blockquote><p>%s</p></blockquote>\n",storageInline(n.Text,p,attachments));case "hr":b.WriteString("<hr/>\n");case "code":code:=strings.ReplaceAll(n.Text,"]]>","]]]]><![CDATA[>");fmt.Fprintf(&b,"<ac:structured-macro ac:name=\"code\"><ac:parameter ac:name=\"language\">%s</ac:parameter><ac:plain-text-body><![CDATA[%s]]></ac:plain-text-body></ac:structured-macro>\n",html.EscapeString(n.Meta["language"]),code);case "info","warning","note":title:=strings.ToUpper(n.Type);if n.Meta!=nil&&n.Meta["kind"]!=""{title=strings.ToUpper(n.Meta["kind"])};fmt.Fprintf(&b,"<ac:structured-macro ac:name=\"panel\"><ac:parameter ac:name=\"title\">%s</ac:parameter><ac:rich-text-body><p>%s</p></ac:rich-text-body></ac:structured-macro>\n",html.EscapeString(title),storageInline(n.Text,p,attachments));case "wrap":renderWrapStorage(&b,n,p,attachments);case "include":fmt.Fprintf(&b,"<p>[DOKUWIKI INCLUDE: %s]</p>\n",html.EscapeString(n.Target));case "nowiki":fmt.Fprintf(&b,"<pre>%s</pre>\n",html.EscapeString(n.Text));case "unknown_plugin":fmt.Fprintf(&b,"<p><strong>Unsupported plugin: %s</strong></p><pre>%s</pre>\n",html.EscapeString(n.Plugin),html.EscapeString(n.Raw))}};return b.String()}
func renderWrapStorage(b *strings.Builder,n model.Node,p model.Page,a map[string]string){classes:="";if n.Meta!=nil{classes=n.Meta["classes"]};fmt.Fprintf(b,"<div class=\"dokuwiki-wrap %s\">",html.EscapeString(classes));for _,c:=range n.Children{switch c.Type{case "paragraph":fmt.Fprintf(b,"<p>%s</p>",storageInline(c.Text,p,a));case "heading":fmt.Fprintf(b,`<h%s id="%s">%s</h%s>`,c.Level,anchorID(c.Text),storageInline(c.Text,p,a),c.Level);case "wrap":renderWrapStorage(b,c,p,a);default:if c.Text!=""{fmt.Fprintf(b,"<p>%s</p>",storageInline(c.Text,p,a))}}};b.WriteString("</div>\n")}
func storageInline(s string,p model.Page,attachments map[string]string)string{out:=html.EscapeString(s);out=confluenceLink.ReplaceAllStringFunc(out,func(raw string)string{m:=confluenceLink.FindStringSubmatch(html.UnescapeString(raw));if len(m)==0{return raw};target:=normalizeURL(m[1]);label:=m[2];if label==""{label=target};if isExternalLink(target){return fmt.Sprintf(`<a href="%s">%s</a>`,html.EscapeString(target),storageInline(label,p,attachments))};if strings.HasPrefix(strings.TrimSpace(target),"#"){return fmt.Sprintf(`<a href="#%s">%s</a>`,html.EscapeString(anchorID(strings.TrimPrefix(strings.TrimSpace(target),"#"))),storageInline(label,p,attachments))};return fmt.Sprintf(`<span>[DOKUWIKI LINK: %s]</span>`,html.EscapeString(resolveTarget(p.ID,target)))})
out=confluenceMedia.ReplaceAllStringFunc(out,func(raw string)string{m:=confluenceMedia.FindStringSubmatch(html.UnescapeString(raw));if len(m)==0{return raw};target:=normalizeMediaTarget(resolveTarget(p.ID,m[1]));name:=attachments[target];if name==""{name=filepath.Base(strings.ReplaceAll(target,":","/"))};return fmt.Sprintf(`<ac:image><ri:attachment ri:filename="%s"/></ac:image>`,html.EscapeString(name))})
out=confluenceFootnote.ReplaceAllStringFunc(out,func(raw string)string{m:=confluenceFootnote.FindStringSubmatch(html.UnescapeString(raw));if len(m)==0{return raw};return `<sup class="footnote">`+storageInline(m[1],p,attachments)+`</sup>`});out=confluenceBold.ReplaceAllString(out,`<strong>$1</strong>`);out=confluenceItalic.ReplaceAllString(out,`<em>$1</em>`);out=confluenceUnderline.ReplaceAllString(out,`<u>$1</u>`);out=confluenceMono.ReplaceAllString(out,`<code>$1</code>`);out=confluenceStrike.ReplaceAllString(out,`<del>$1</del>`);return out}
func resolveTarget(current,target string)string{target=strings.TrimSpace(target);if strings.HasPrefix(target,":"){return strings.TrimPrefix(target,":")};if strings.HasPrefix(target,"#"){return target};if strings.Contains(target,":"){return target};if i:=strings.LastIndex(current,":");i>=0{return current[:i+1]+target};return target}
